[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_calculator = "AyWDkUYKAx8SWdwiLywcvTXD7We7ZkDiC6PLc7pGUHtT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run mocha tests/**/*.js"
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
